/* LearnNaija AI Tutor — multi-mode, local fallback, secure server AI */
const languageNames={yoruba:"Yorùbá",igbo:"Igbo",hausa:"Hausa"};
const phrases={
 yoruba:[{native:"Báwo ni?",english:"How are you?"},{native:"Ẹ káàárọ̀",english:"Good morning"},{native:"Ẹ ṣé",english:"Thank you"},{native:"Orúkọ mi ni Oba",english:"My name is Oba"}],
 igbo:[{native:"Ndeewo",english:"Hello / greetings"},{native:"Kedụ?",english:"How are you?"},{native:"Daalụ",english:"Thank you"},{native:"Aha m bụ Oba",english:"My name is Oba"}],
 hausa:[{native:"Sannu",english:"Hello / welcome"},{native:"Yaya kake?",english:"How are you?"},{native:"Na gode",english:"Thank you"},{native:"Sunana Oba",english:"My name is Oba"}]
};
let currentLanguage=localStorage.getItem("learnnaija_language")||"yoruba",mode="conversation",phraseIndex=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const chatArea=$("#chat-area"),chatForm=$("#chat-form"),chatInput=$("#chat-input"),welcome=$("#welcome-message"),status=$("#tutor-status"),voiceButton=$("#voice-button");
function langCode(){return currentLanguage==="yoruba"?"yo-NG":currentLanguage==="igbo"?"ig-NG":"ha-NG"}
function speak(text){if(!("speechSynthesis"in window)){window.LearnNaija?.showToast("Spoken playback is not available in this browser.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=langCode();u.rate=.76;speechSynthesis.speak(u)}
function addMessage(text,type="tutor"){const w=document.createElement("div");w.className=`chat-message ${type==="user"?"user-message":"tutor-message"}`;w.innerHTML=type==="tutor"?`<div class="message-avatar"><i class="bi bi-stars"></i></div><div class="message-bubble"><span class="message-label">AI TUTOR</span><p></p></div>`:`<div class="message-bubble"><p></p></div>`;w.querySelector("p").textContent=text;chatArea.appendChild(w);chatArea.scrollTop=chatArea.scrollHeight}
function currentPhrase(){return phrases[currentLanguage][phraseIndex%phrases[currentLanguage].length]}
function localResponse(message){const p=currentPhrase(),n=languageNames[currentLanguage],m=mode;if(m==="quiz"||/quiz|test/i.test(message))return `🧠 Quick quiz: what does “${p.native}” mean in ${n}? Reply with your answer.`;if(m==="teach"||/teach|lesson|learn/i.test(message))return `Let’s learn: “${p.native}” means “${p.english}”. Listen first, then say it aloud. Example: use it when you meet someone.`;if(m==="pronunciation"||/pronoun|speak|say/i.test(message))return `🎤 Your phrase is “${p.native}”. Tap the mic and say it. I’ll compare the browser transcript with the target and give you a simple retry tip.`;if(m==="translate"||/meaning|translate/i.test(message))return `Send me a ${n} word or phrase. I’ll give you the English meaning, context and a simple example.`;phraseIndex++;return `Nice. Let’s have a simple ${n} conversation. Start with “${p.native}” and I’ll reply at beginner level.`}
async function askTutor(message){try{const response=await fetch("/api/ai/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,language:currentLanguage,mode,history:[...chatArea.querySelectorAll(".message-bubble p")].slice(-10).map((x,i)=>({role:i%2===0?"assistant":"user",content:x.textContent}))})});if(response.ok){const data=await response.json();if(data.reply)return data.reply}}catch{}return localResponse(message)}
function setLanguage(language){currentLanguage=language;localStorage.setItem("learnnaija_language",language);$$(".language-tab").forEach(t=>{const active=t.dataset.language===language;t.classList.toggle("active",active);t.setAttribute("aria-selected",String(active))});status.textContent=`${languageNames[language]} ${mode} ready`;welcome.textContent=`${language==="yoruba"?"Báwo":language==="igbo"?"Ndewo":"Sannu"} Oba 👋 I’m ready. Choose a mode or ask me anything in ${languageNames[language]}.`;chatInput.placeholder=`Ask about ${languageNames[language]}...`}
function setMode(next){mode=next;$$(".ai-mode").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));status.textContent=`${languageNames[currentLanguage]} ${mode} ready`;if(mode==="pronunciation")chatInput.placeholder="Ask for a phrase to pronounce...";else if(mode==="quiz")chatInput.placeholder="Answer the quiz or ask for another...";else chatInput.placeholder=`Ask about ${languageNames[currentLanguage]}...`}
function recognition(){return window.SpeechRecognition||window.webkitSpeechRecognition}
function startVoice(){const R=recognition();if(!R){addMessage("Voice input is not supported here. Try Chrome or Edge.");return}const r=new R();r.lang=langCode();r.interimResults=false;r.maxAlternatives=1;voiceButton.classList.add("recording");status.textContent="Listening…";r.onresult=e=>{const heard=e.results[0][0].transcript;chatInput.value=heard;addMessage(`I heard: “${heard}” 🎤`,"tutor");checkPronunciation(heard)};r.onerror=()=>addMessage("I couldn't hear that clearly. Try again in a quiet place.");r.onend=()=>{voiceButton.classList.remove("recording");status.textContent=`${languageNames[currentLanguage]} ${mode} ready`};r.start()}
function levenshtein(a,b){a=a.toLowerCase().replace(/[^a-zà-ž' ]/g,"").trim();b=b.toLowerCase().replace(/[^a-zà-ž' ]/g,"").trim();const d=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=d[0];d[0]=i;for(let j=1;j<=b.length;j++){const t=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=t}}return d[b.length]}
function checkPronunciation(heard){const target=currentPhrase().native,score=Math.max(0,Math.round((1-levenshtein(heard,target)/Math.max(target.length,1))*100));addMessage(`Speech match: ${score}%. Target: “${target}”. This compares text transcripts, not actual acoustic pronunciation. Listen again and retry.`);speak(target)}
$$(".language-tab").forEach(b=>b.addEventListener("click",()=>setLanguage(b.dataset.language)));
$$(".ai-mode").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));
$$(".quick-action").forEach(b=>b.addEventListener("click",()=>{chatInput.value=b.dataset.prompt;chatForm.requestSubmit()}));
$("#clear-chat").addEventListener("click",()=>{chatArea.innerHTML=`<div class="chat-message tutor-message"><div class="message-avatar"><i class="bi bi-stars"></i></div><div class="message-bubble"><span class="message-label">AI TUTOR</span><p>${languageNames[currentLanguage]} session reset. What shall we practise?</p></div></div>`;phraseIndex=0});
chatForm.addEventListener("submit",async e=>{e.preventDefault();const m=chatInput.value.trim();if(!m)return;addMessage(m,"user");chatInput.value="";status.textContent="Thinking…";const reply=await askTutor(m);addMessage(reply);status.textContent=`${languageNames[currentLanguage]} ${mode} ready`;window.LearnNaija?.touchActivity("ai")});
voiceButton.addEventListener("click",startVoice);
setLanguage(currentLanguage);setMode(mode);