/* LearnNaija Home — responsive app dashboard */
(()=> {
 const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
 const home=$("#home"); if(!home)return;
 home.innerHTML=`
 <div class="home-v2-profile"><div class="home-v2-identity"><button class="home-v2-avatar" id="home-v2-avatar" type="button" aria-label="Change profile picture">O</button><input id="home-v2-avatar-input" type="file" accept="image/*" hidden><div><h1 class="home-v2-name">Oba <span class="home-v2-status"><i class="bi bi-check2"></i></span></h1><p class="home-v2-sub">Your Nigerian language journey · Keep going</p></div></div><button class="icon-button home-v2-bell" id="home-v2-notifications" type="button" aria-label="View notifications"><i class="bi bi-bell"></i></button></div>
 <div class="home-v2-progress"><div class="home-v2-stat"><strong><i class="bi bi-stars"></i><span id="home-v2-xp">240</span></strong><span>XP</span></div><div class="home-v2-stat"><strong><i class="bi bi-fire"></i><span id="home-v2-streak">5</span></strong><span>Day streak</span></div><div class="home-v2-stat"><strong><i class="bi bi-book"></i><span id="home-v2-vocab">24</span></strong><span>Vocabulary</span></div><div class="home-v2-stat"><strong><i class="bi bi-check2-circle"></i><span id="home-v2-lessons">0</span></strong><span>Lessons</span></div></div>
 <section class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">KEEP LEARNING</p><h2>Lessons</h2></div><button class="home-v2-link" id="home-v2-see-lessons" type="button">See all <i class="bi bi-arrow-right"></i></button></div><article class="home-v2-lesson"><div class="home-v2-lesson-top"><span class="home-v2-tag">NEXT UP · YORÙBÁ</span><span class="home-v2-xp">+20 XP</span></div><div class="home-v2-lesson-main"><span class="home-v2-lesson-icon"><i class="bi bi-chat-heart"></i></span><div><h3 id="home-v2-lesson-name">Greetings</h3><p id="home-v2-lesson-detail">Open a conversation with warmth.</p></div></div><div class="home-v2-lesson-progress"><div class="progress-track"><div id="home-v2-progress-fill"></div></div><span id="home-v2-progress-text">0%</span></div><button class="home-v2-continue" id="home-v2-continue" type="button">Continue lesson <i class="bi bi-arrow-up-right"></i></button></article></section>
 <section class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">YOUR COACH</p><h2>AI Language Coach</h2></div></div><button class="home-v2-ai" id="home-v2-ai-card" type="button"><span class="home-v2-ai-orb"><i class="bi bi-mic-fill"></i></span><span class="home-v2-ai-copy"><strong>Talk, listen and learn</strong><span>Conversation, quizzes, translations and speaking practice in Yorùbá, Igbo or Hausa.</span></span><i class="bi bi-arrow-up-right home-v2-ai-arrow"></i></button></section>
 <section class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">YOUR NUMBERS</p><h2>Stats</h2></div><button class="home-v2-link" id="home-v2-open-stats" type="button">Full stats <i class="bi bi-arrow-right"></i></button></div><div class="home-v2-stat-grid"><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-trophy"></i></span><strong id="home-v2-stat-xp">240</strong><span>Total XP earned</span></div><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-translate"></i></span><strong id="home-v2-stat-languages">3</strong><span>Languages available</span></div></div></section>`;
 const main=home.parentElement;
 let stats=$("#stats",main);
 if(!stats){stats=document.createElement("section");stats.id="stats";stats.className="app-screen home-v2-stats-screen";stats.innerHTML=`
 <div class="screen-heading"><p class="eyebrow">YOUR PROGRESS</p><h1 id="stats-title">See how you're <em>growing.</em></h1><span>Lessons, practice and your learning habit in one place.</span></div>
 <div class="home-v2-stats-hero"><div class="home-v2-big-stat"><small>TOTAL XP</small><strong id="stats-xp">240</strong></div><div class="home-v2-big-stat alt"><small>STREAK</small><strong id="stats-streak">5 days</strong></div></div>
 <div class="home-v2-chart"><div class="home-v2-chart-head"><strong>Recent activity</strong><span>Last 7 days</span></div><div class="home-v2-bars" id="home-v2-bars"></div></div>
 <div class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">BREAKDOWN</p><h2>Learning stats</h2></div></div><div class="home-v2-stat-grid"><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-book"></i></span><strong id="stats-lessons">0</strong><span>Lessons completed</span></div><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-translate"></i></span><strong id="stats-vocab">24</strong><span>Vocabulary words</span></div></div></div>`;
 main.appendChild(stats)}
 const old=$(".bottom-nav");if(old)old.remove();
 const nav=document.createElement("nav");nav.className="home-v2-nav";nav.setAttribute("aria-label","Primary navigation");nav.innerHTML=`<a href="#home" class="active"><i class="bi bi-house-door-fill"></i><span>Home</span></a><a href="#learn"><i class="bi bi-book"></i><span>Learn</span></a><a href="ai-tutor.html" class="home-v2-ai-nav" aria-label="Open AI Tutor"><span class="home-v2-ai-button"><i class="bi bi-mic-fill"></i></span><span>AI</span></a><a href="#practice"><i class="bi bi-lightning-charge"></i><span>Practice</span></a><a href="#profile"><i class="bi bi-person"></i><span>Profile</span></a>`;document.querySelector(".app-shell").appendChild(nav);
 function refresh(){const api=window.LearnNaija;if(!api)return;const u=api.getUser(),done=api.allCompleted(),xp=u.xp||0,streak=u.streak||0,vocab=api.vocabularyCount();$("#home-v2-xp").textContent=xp;$("#home-v2-stat-xp").textContent=xp;$("#home-v2-streak").textContent=streak;$("#home-v2-vocab").textContent=vocab;$("#home-v2-lessons").textContent=done;$("#stats-xp").textContent=xp;$("#stats-streak").textContent=`${streak} days`;$("#stats-lessons").textContent=done;$("#stats-vocab").textContent=vocab;const yDone=api.getProgress().completedLessons.length;const pct=Math.round(yDone/4*100);$("#home-v2-progress-fill").style.width=`${pct}%`;$("#home-v2-progress-text").textContent=`${pct}%`;const activity=u.weeklyActivity||{},bars=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);bars.push({key,label:d.toLocaleDateString(undefined,{weekday:"short"}).slice(0,1),value:activity[key]||0})}const max=Math.max(1,...bars.map(x=>x.value));$("#home-v2-bars").innerHTML=bars.map(x=>`<div class="home-v2-chart-col"><div class="home-v2-bar ${x.value===max&&x.value>0?"today":""}" style="--h:${Math.max(12,x.value/max*88)}%"></div><label>${x.label}</label></div>`).join("")}
 const saved=localStorage.getItem("learnnaija_avatar"),avatar=$("#home-v2-avatar");if(saved){avatar.innerHTML=`<img src="${saved}" alt="Oba profile picture">`;const p=$("#profile .avatar");if(p)p.innerHTML=`<img src="${saved}" alt="Oba profile picture"><span></span>`}
 avatar.addEventListener("click",()=>$("#home-v2-avatar-input").click());$("#home-v2-avatar-input").addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{localStorage.setItem("learnnaija_avatar",reader.result);avatar.innerHTML=`<img src="${reader.result}" alt="Oba profile picture">`};reader.readAsDataURL(f)});
 nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",e=>{if(a.getAttribute("href")==="ai-tutor.html")return;e.preventDefault();const id=a.getAttribute("href").slice(1);if(window.LearnNaija?.showScreen)window.LearnNaija.showScreen(id);nav.querySelectorAll("a").forEach(x=>x.classList.toggle("active",x===a))}));
 $("#home-v2-see-lessons").addEventListener("click",()=>window.LearnNaija?.showScreen("learn"));$("#home-v2-open-stats").addEventListener("click",()=>window.LearnNaija?.showScreen("stats"));$("#home-v2-ai-card").addEventListener("click",()=>location.href="ai-tutor.html");$("#home-v2-continue").addEventListener("click",()=>{if(window.LearnNaija)startLesson(nextLesson())});$("#home-v2-notifications").addEventListener("click",()=>openModal("notifications"));
 refresh();window.addEventListener("learnnaija:progress",refresh);
})();