/* LearnNaija Home v2 — reorganise the existing app into the new mobile-first dashboard */
(() => {
  const $ = (selector, parent = document) => parent.querySelector(selector);
  const home = $("#home");
  if (!home) return;
  const user = () => { try { return { xp: 240, streak: 5, ...(JSON.parse(localStorage.getItem("learnnaija_user")) || {}) }; } catch { return { xp: 240, streak: 5 }; } };

  home.innerHTML = `
    <div class="home-v2-profile"><div class="home-v2-identity"><div class="home-v2-avatar" aria-label="Oba profile photo">O</div><div><h1 class="home-v2-name">Oba <span class="home-v2-status" title="Active learner"><i class="bi bi-check2"></i></span></h1><p class="home-v2-sub">Yorùbá beginner · Keep the streak alive</p></div></div><button class="icon-button home-v2-bell" id="home-v2-notifications" type="button" aria-label="View notifications"><i class="bi bi-bell"></i></button></div>
    <div class="home-v2-progress" aria-label="Your learning progress"><div class="home-v2-stat"><strong><i class="bi bi-stars"></i><span id="home-v2-xp">240</span></strong><span>XP</span></div><div class="home-v2-stat"><strong><i class="bi bi-fire"></i><span id="home-v2-streak">5</span></strong><span>Day streak</span></div><div class="home-v2-stat"><strong><i class="bi bi-book"></i><span id="home-v2-vocab">24</span></strong><span>Vocabulary</span></div><div class="home-v2-stat"><strong><i class="bi bi-check2-circle"></i><span id="home-v2-lessons">0</span></strong><span>Lessons</span></div></div>
    <section class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">KEEP LEARNING</p><h2>Lessons</h2></div><button class="home-v2-link" id="home-v2-see-lessons" type="button">See all <i class="bi bi-arrow-right"></i></button></div><article class="home-v2-lesson"><div class="home-v2-lesson-top"><span class="home-v2-tag">YORÙBÁ · UNIT 01</span><span class="home-v2-xp">+20 XP</span></div><div class="home-v2-lesson-main"><span class="home-v2-lesson-icon"><i class="bi bi-chat-heart"></i></span><div><h3 id="home-v2-lesson-name">Greetings</h3><p id="home-v2-lesson-detail">Open a conversation with warmth.</p></div></div><div class="home-v2-lesson-progress"><div class="progress-track"><div id="home-v2-progress-fill"></div></div><span id="home-v2-progress-text">0%</span></div><button class="home-v2-continue" id="home-v2-continue" type="button">Continue lesson <i class="bi bi-arrow-up-right"></i></button></article></section>
    <section class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">YOUR COACH</p><h2>AI Language Coach</h2></div></div><button class="home-v2-ai" id="home-v2-ai-card" type="button"><span class="home-v2-ai-orb"><i class="bi bi-mic-fill"></i></span><span class="home-v2-ai-copy"><strong>Talk to your AI tutor</strong><span>Practice Yorùbá, ask questions, get feedback and build confidence through conversation.</span></span><i class="bi bi-arrow-up-right home-v2-ai-arrow"></i></button></section>
    <section class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">YOUR NUMBERS</p><h2>Stats</h2></div><button class="home-v2-link" id="home-v2-open-stats" type="button">Full stats <i class="bi bi-arrow-right"></i></button></div><div class="home-v2-stat-grid"><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-trophy"></i></span><strong id="home-v2-stat-xp">240</strong><span>Total XP earned</span></div><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-lightning-charge"></i></span><strong id="home-v2-stat-streak">5 days</strong><span>Current streak</span></div></div></section>`;

  const main = home.parentElement;
  if (!$("#stats", main)) {
    const stats = document.createElement("section"); stats.id="stats"; stats.className="app-screen home-v2-stats-screen"; stats.setAttribute("aria-labelledby","stats-title");
    stats.innerHTML=`<div class="screen-heading"><p class="eyebrow">YOUR PROGRESS</p><h1 id="stats-title">See how you're <em>growing.</em></h1><span>Your learning numbers at a glance.</span></div><div class="home-v2-stats-hero"><div class="home-v2-big-stat"><small>TOTAL XP</small><strong id="stats-xp">240</strong></div><div class="home-v2-big-stat alt"><small>STREAK</small><strong id="stats-streak">5 days</strong></div></div><div class="home-v2-chart"><div class="home-v2-chart-head"><strong>Weekly activity</strong><span>Lessons + practice</span></div><div class="home-v2-bars"><div class="home-v2-chart-col"><div class="home-v2-bar" style="--h:35%"></div><label>M</label></div><div class="home-v2-chart-col"><div class="home-v2-bar" style="--h:52%"></div><label>T</label></div><div class="home-v2-chart-col"><div class="home-v2-bar" style="--h:42%"></div><label>W</label></div><div class="home-v2-chart-col"><div class="home-v2-bar" style="--h:68%"></div><label>T</label></div><div class="home-v2-chart-col"><div class="home-v2-bar" style="--h:76%"></div><label>F</label></div><div class="home-v2-chart-col"><div class="home-v2-bar today" style="--h:88%"></div><label>S</label></div><div class="home-v2-chart-col"><div class="home-v2-bar" style="--h:18%"></div><label>S</label></div></div></div><div class="home-v2-section"><div class="home-v2-section-head"><div><p class="eyebrow">BREAKDOWN</p><h2>Learning stats</h2></div></div><div class="home-v2-stat-grid"><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-book"></i></span><strong id="stats-lessons">0</strong><span>Lessons completed</span></div><div class="home-v2-stat-card"><span class="icon"><i class="bi bi-translate"></i></span><strong id="stats-vocab">24</strong><span>Words in vocabulary</span></div></div></div>`;
    main.appendChild(stats);
  }

  const oldNav=$(".bottom-nav"); if(oldNav) oldNav.remove();
  const nav=document.createElement("nav"); nav.className="home-v2-nav"; nav.setAttribute("aria-label","Primary navigation");
  nav.innerHTML=`<a href="#home" class="active"><i class="bi bi-house-door-fill"></i><span>Home</span></a><a href="#learn"><i class="bi bi-book"></i><span>Learn</span></a><a href="ai-tutor.html" class="home-v2-ai-nav" aria-label="Open AI Tutor"><span class="home-v2-ai-button"><i class="bi bi-mic-fill"></i></span><span>AI</span></a><a href="#practice"><i class="bi bi-lightning-charge"></i><span>Practice</span></a><a href="#profile"><i class="bi bi-person"></i><span>Profile</span></a>`;
  document.querySelector(".app-shell").appendChild(nav);

  function refresh(){const u=user();let lessonsDone=0;try{lessonsDone=JSON.parse(localStorage.getItem("learnnaija_yoruba_progress"))?.completedLessons?.length||0;}catch{}const progress=Math.round((lessonsDone/4)*100);["#home-v2-xp","#home-v2-stat-xp","#stats-xp"].forEach(s=>{const el=$(s);if(el)el.textContent=u.xp;});["#home-v2-streak","#stats-streak"].forEach(s=>{const el=$(s);if(el)el.textContent=`${u.streak} days`;});["#home-v2-lessons","#stats-lessons"].forEach(s=>{const el=$(s);if(el)el.textContent=lessonsDone;});const fill=$("#home-v2-progress-fill");if(fill)fill.style.width=`${progress}%`;const pct=$("#home-v2-progress-text");if(pct)pct.textContent=`${progress}%`;const statStreak=$("#home-v2-stat-streak");if(statStreak)statStreak.textContent=`${u.streak} days`;}
  refresh();
  function go(id){if(typeof showScreen==="function")showScreen(id);}
  nav.querySelectorAll("a").forEach(item=>item.addEventListener("click",event=>{const href=item.getAttribute("href");if(href==="ai-tutor.html")return;event.preventDefault();go(href.slice(1));nav.querySelectorAll("a").forEach(a=>a.classList.toggle("active",a===item));}));
  $("#home-v2-see-lessons").addEventListener("click",()=>go("learn")); $("#home-v2-open-stats").addEventListener("click",()=>go("stats")); $("#home-v2-ai-card").addEventListener("click",()=>{window.location.href="ai-tutor.html";});
  $("#home-v2-continue").addEventListener("click",()=>{if(typeof nextLesson==="function"&&typeof startLesson==="function")startLesson(nextLesson());}); $("#home-v2-notifications").addEventListener("click",()=>{if(typeof openModal==="function")openModal("notifications");});
})();
